import { BOOKING_STATUS, LISTING_STATUS, LISTING_TYPE, OCCURRENCE_STATUS, USER_ROLE } from "@/lib/enums";

const inDays = (days, hour = 19, minute = 0, durationHours = 3) => {
  const start = new Date();
  start.setDate(start.getDate() + days);
  start.setHours(hour, minute, 0, 0);
  const end = new Date(start.getTime() + durationHours * 60 * 60 * 1000);
  return { start: start.toISOString(), end: end.toISOString() };
};

export const mockCities = [
  {
    id: "city-gurugram",
    name: "Gurugram",
    state: "Haryana",
    image_url:
      "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1200&q=80",
    is_active: true,
  },
  {
    id: "city-mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    image_url:
      "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?auto=format&fit=crop&w=1200&q=80",
    is_active: true,
  },
];

export const mockVenues = [
  {
    id: "venue-pvr-ambience",
    name: "PVR Ambience",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_type: "THEATER",
    latitude: 28.5054,
    longitude: 77.0952,
    is_active: true,
  },
  {
    id: "venue-gymkhana",
    name: "Gymkhana Club",
    city_id: "city-gurugram",
    address: "Sector 29, Gurugram",
    venue_type: "EVENT_SPACE",
    latitude: 28.4675,
    longitude: 77.0735,
    is_active: true,
  },
  {
    id: "venue-comorin",
    name: "Comorin",
    city_id: "city-gurugram",
    address: "Two Horizon Center, Gurugram",
    venue_type: "RESTAURANT",
    latitude: 28.4582,
    longitude: 77.0905,
    is_active: true,
  },
  {
    id: "venue-karting",
    name: "F9 Karting Arena",
    city_id: "city-gurugram",
    address: "Sector 59, Gurugram",
    venue_type: "ACTIVITY_AREA",
    latitude: 28.4143,
    longitude: 77.0933,
    is_active: true,
  },
];

export const mockListings = [
  {
    id: "listing-movie-mardaani3",
    type: LISTING_TYPE.MOVIE,
    title: "Mardaani 3",
    description: "Shivani returns to investigate a nationwide crime network.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_id: "venue-pvr-ambience",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1489599511591-4b4b64f14f7b?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 220,
    price_max: 450,
    currency: "INR",
    category: "Action",
    offer_text: "Flat 20% off up to Rs 200",
    smart_date_label: "Tonight, 7:30 PM",
    is_wishlisted: false,
    is_featured: true,
    metadata: { language: "Hindi", certification: "UA16+", duration_min: 135 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-movie-border2",
    type: LISTING_TYPE.MOVIE,
    title: "Border 2",
    description: "A high-intensity war drama inspired by true events.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_id: "venue-pvr-ambience",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 180,
    price_max: 380,
    currency: "INR",
    category: "War",
    offer_text: "",
    smart_date_label: "Tomorrow, 6:45 PM",
    is_wishlisted: true,
    is_featured: true,
    metadata: { language: "Hindi", certification: "UA13+", duration_min: 142 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-movie-tuyaamain",
    type: LISTING_TYPE.MOVIE,
    title: "Tu Yaa Main",
    description: "A romantic thriller packed with twists.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_id: "venue-pvr-ambience",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1533928298208-27ff66555d8d?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 200,
    price_max: 420,
    currency: "INR",
    category: "Thriller",
    offer_text: "",
    smart_date_label: "Fri, 9:20 PM",
    is_wishlisted: false,
    is_featured: true,
    metadata: { language: "Hindi", certification: "UA16+", duration_min: 128 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-event-mltr",
    type: LISTING_TYPE.EVENT,
    title: "Michael Learns to Rock Live",
    description: "An evening with timeless pop anthems.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Gymkhana Club, Gurugram",
    venue_id: "venue-gymkhana",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 1999,
    price_max: 4999,
    currency: "INR",
    category: "Music",
    offer_text: "Group of 3 save Rs 300",
    smart_date_label: "Sun, 6:00 PM",
    is_wishlisted: false,
    is_featured: true,
    metadata: { organizer_name: "Live Nation India" },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-event-aujla",
    type: LISTING_TYPE.EVENT,
    title: "Karan Aujla P-Pop Culture Tour",
    description: "Live in Delhi NCR with full production.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Jawaharlal Nehru Stadium, Delhi",
    venue_id: "venue-gymkhana",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 2499,
    price_max: 6999,
    currency: "INR",
    category: "Music",
    offer_text: "",
    smart_date_label: "Sat, 6:00 PM",
    is_wishlisted: true,
    is_featured: true,
    metadata: { organizer_name: "TicketLive" },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-event-comiccon",
    type: LISTING_TYPE.EVENT,
    title: "Comic Con Delhi",
    description: "Comics, cosplay, and creators.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "NSIC Grounds, Okhla",
    venue_id: "venue-gymkhana",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 799,
    price_max: 2499,
    currency: "INR",
    category: "Festival",
    offer_text: "",
    smart_date_label: "Fri, 11:00 AM",
    is_wishlisted: false,
    is_featured: false,
    metadata: { organizer_name: "Comic Con India" },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-activity-karting",
    type: LISTING_TYPE.ACTIVITY,
    title: "F9 Go Karting",
    description: "Race-ready tracks and timed laps.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Sector 59, Gurugram",
    venue_id: "venue-karting",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 675,
    price_max: 1250,
    currency: "INR",
    category: "Adventure",
    offer_text: "Flat 25% off on select tickets",
    smart_date_label: "Daily, multiple slots",
    is_wishlisted: false,
    is_featured: true,
    metadata: { duration_min: 30 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-activity-museum",
    type: LISTING_TYPE.ACTIVITY,
    title: "Museum of Illusions",
    description: "Interactive visual illusion exhibits.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Connaught Place, Delhi",
    venue_id: "venue-karting",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 590,
    price_max: 950,
    currency: "INR",
    category: "Family",
    offer_text: "",
    smart_date_label: "Multiple dates",
    is_wishlisted: false,
    is_featured: false,
    metadata: { duration_min: 90 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-restaurant-comorin",
    type: LISTING_TYPE.RESTAURANT,
    title: "Comorin",
    description: "Modern Indian food and cocktails.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Two Horizon Center, Gurugram",
    venue_id: "venue-comorin",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 1200,
    price_max: 2800,
    currency: "INR",
    category: "Dining",
    offer_text: "Complimentary dessert with table booking",
    smart_date_label: "Open till 11:30 PM",
    is_wishlisted: true,
    is_featured: true,
    metadata: { cuisines: ["Indian", "Contemporary"], average_cost_for_two: 2500 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-restaurant-kode",
    type: LISTING_TYPE.RESTAURANT,
    title: "Kuuraku",
    description: "Japanese robata and hand-crafted plates.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Cyber Hub, Gurugram",
    venue_id: "venue-comorin",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 1300,
    price_max: 2400,
    currency: "INR",
    category: "Dining",
    offer_text: "",
    smart_date_label: "Open till midnight",
    is_wishlisted: false,
    is_featured: false,
    metadata: { cuisines: ["Japanese"], average_cost_for_two: 2300 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-movie-war2",
    type: LISTING_TYPE.MOVIE,
    title: "War 2",
    description: "A globe-spanning spy action blockbuster.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_id: "venue-pvr-ambience",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 240,
    price_max: 520,
    currency: "INR",
    category: "Action",
    offer_text: "Flat Rs 100 off on premium seats",
    smart_date_label: "Sat, 10:10 PM",
    is_wishlisted: false,
    is_featured: true,
    metadata: { language: "Hindi", certification: "UA16+", duration_min: 156 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-movie-stree3",
    type: LISTING_TYPE.MOVIE,
    title: "Stree 3",
    description: "The horror-comedy franchise returns with new mysteries.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_id: "venue-pvr-ambience",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 210,
    price_max: 460,
    currency: "INR",
    category: "Horror",
    offer_text: "",
    smart_date_label: "Fri, 8:25 PM",
    is_wishlisted: false,
    is_featured: false,
    metadata: { language: "Hindi", certification: "UA13+", duration_min: 134 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-movie-don3",
    type: LISTING_TYPE.MOVIE,
    title: "Don 3",
    description: "A sleek heist thriller in the Don universe.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_id: "venue-pvr-ambience",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 230,
    price_max: 500,
    currency: "INR",
    category: "Thriller",
    offer_text: "Buy 2 get popcorn combo",
    smart_date_label: "Sun, 7:00 PM",
    is_wishlisted: false,
    is_featured: true,
    metadata: { language: "Hindi", certification: "UA16+", duration_min: 148 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-movie-noentry2",
    type: LISTING_TYPE.MOVIE,
    title: "No Entry 2",
    description: "A chaotic comedy sequel with big laughs.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Ambience Mall, Gurugram",
    venue_id: "venue-pvr-ambience",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1460881680858-30d872d5b530?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 180,
    price_max: 380,
    currency: "INR",
    category: "Comedy",
    offer_text: "",
    smart_date_label: "Mon, 9:00 PM",
    is_wishlisted: false,
    is_featured: false,
    metadata: { language: "Hindi", certification: "UA13+", duration_min: 132 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-event-arijit-live",
    type: LISTING_TYPE.EVENT,
    title: "Arijit Singh Live",
    description: "A soulful live concert evening in NCR.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Gymkhana Club, Gurugram",
    venue_id: "venue-gymkhana",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 2999,
    price_max: 8999,
    currency: "INR",
    category: "Music",
    offer_text: "Early bird ending soon",
    smart_date_label: "Next week, 7:30 PM",
    is_wishlisted: false,
    is_featured: true,
    metadata: { organizer_name: "Live Nation India" },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-event-standup-night",
    type: LISTING_TYPE.EVENT,
    title: "Standup Night Special",
    description: "Top comics performing back-to-back sets.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Sector 29, Gurugram",
    venue_id: "venue-gymkhana",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 699,
    price_max: 1999,
    currency: "INR",
    category: "Comedy",
    offer_text: "Flat 20% off on group bookings",
    smart_date_label: "Sat, 8:00 PM",
    is_wishlisted: false,
    is_featured: false,
    metadata: { organizer_name: "Laugh Labs" },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-event-food-fest",
    type: LISTING_TYPE.EVENT,
    title: "Gurugram Food Festival",
    description: "Street food, live music and chef pop-ups.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Leisure Valley, Gurugram",
    venue_id: "venue-gymkhana",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 399,
    price_max: 1499,
    currency: "INR",
    category: "Festival",
    offer_text: "",
    smart_date_label: "Sun, 12:00 PM",
    is_wishlisted: false,
    is_featured: false,
    metadata: { organizer_name: "City Eats" },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-activity-bowling",
    type: LISTING_TYPE.ACTIVITY,
    title: "Yes Minister Bowling",
    description: "Bowling lanes with arcade and cafe access.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Essex Farms, Gurugram",
    venue_id: "venue-karting",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1549057446-9f5c6ac91a04?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 399,
    price_max: 999,
    currency: "INR",
    category: "Family",
    offer_text: "Buy 3 games, get 1 free",
    smart_date_label: "Daily, multiple slots",
    is_wishlisted: false,
    is_featured: true,
    metadata: { duration_min: 60 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-activity-trampoline",
    type: LISTING_TYPE.ACTIVITY,
    title: "Sky Jump Trampoline Park",
    description: "Wall jumps, dodgeball and foam pits.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Sector 52, Gurugram",
    venue_id: "venue-karting",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1526679491681-9de7d89c1c0a?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 550,
    price_max: 1450,
    currency: "INR",
    category: "Adventure",
    offer_text: "",
    smart_date_label: "Mon-Fri, hourly slots",
    is_wishlisted: false,
    is_featured: false,
    metadata: { duration_min: 45 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-activity-pottery",
    type: LISTING_TYPE.ACTIVITY,
    title: "Pottery And Paint Workshop",
    description: "Guided ceramic shaping and painting sessions.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "DLF Phase 4, Gurugram",
    venue_id: "venue-karting",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 799,
    price_max: 1699,
    currency: "INR",
    category: "Workshops",
    offer_text: "Weekday bundle available",
    smart_date_label: "Fri-Sun, batch sessions",
    is_wishlisted: false,
    is_featured: false,
    metadata: { duration_min: 120 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-restaurant-carnatic-cafe",
    type: LISTING_TYPE.RESTAURANT,
    title: "Carnatic Cafe",
    description: "South Indian classics and filter coffee.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "32nd Avenue, Gurugram",
    venue_id: "venue-comorin",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 900,
    price_max: 1800,
    currency: "INR",
    category: "Dining",
    offer_text: "Complimentary beverage with lunch combo",
    smart_date_label: "Open till 11:00 PM",
    is_wishlisted: false,
    is_featured: false,
    metadata: { cuisines: ["South Indian"], average_cost_for_two: 1600 },
    status: LISTING_STATUS.PUBLISHED,
  },
  {
    id: "listing-restaurant-smoke-house",
    type: LISTING_TYPE.RESTAURANT,
    title: "Smoke House Deli",
    description: "All-day cafe with continental and bistro favourites.",
    city: "Gurugram",
    city_id: "city-gurugram",
    address: "Cyber Hub, Gurugram",
    venue_id: "venue-comorin",
    timezone: "Asia/Kolkata",
    cover_image_url:
      "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80",
    gallery_image_urls: [],
    price_min: 1100,
    price_max: 2600,
    currency: "INR",
    category: "Dining",
    offer_text: "",
    smart_date_label: "Open till 12:00 AM",
    is_wishlisted: false,
    is_featured: true,
    metadata: { cuisines: ["Continental", "Cafe"], average_cost_for_two: 2200 },
    status: LISTING_STATUS.PUBLISHED,
  },
];

const mardaaniShow1 = inDays(0, 19, 30, 2.3);
const mardaaniShow2 = inDays(1, 21, 5, 2.3);
const borderShow = inDays(2, 18, 45, 2.5);
const tuShow = inDays(3, 20, 10, 2.2);
const mltrShow = inDays(4, 18, 0, 3.5);
const aujlaShow = inDays(8, 18, 30, 3.5);
const comicConDay = inDays(9, 11, 0, 8);
const kartingSlot = inDays(1, 14, 0, 1);
const museumSlot = inDays(2, 13, 0, 1.5);
const comorinSlot = inDays(0, 20, 0, 2);

export const mockOccurrences = [
  {
    id: "occ-mardaani-1",
    listing_id: "listing-movie-mardaani3",
    venue_id: "venue-pvr-ambience",
    city_id: "city-gurugram",
    start_time: mardaaniShow1.start,
    end_time: mardaaniShow1.end,
    provider_sub_location: "Screen 3",
    capacity_total: 120,
    capacity_remaining: 63,
    ticket_pricing: { SILVER: 220, GOLD: 320, RECLINER: 450 },
    seat_layout: {
      rows: ["A", "B", "C", "D", "E", "F", "G", "H"],
      columns: 12,
      categories: [
        { key: "RECLINER", price: 450, color: "#f59e0b", rows: ["A", "B"] },
        { key: "GOLD", price: 320, color: "#3b82f6", rows: ["C", "D", "E"] },
        { key: "SILVER", price: 220, color: "#22c55e", rows: ["F", "G", "H"] },
      ],
    },
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-mardaani-2",
    listing_id: "listing-movie-mardaani3",
    venue_id: "venue-pvr-ambience",
    city_id: "city-gurugram",
    start_time: mardaaniShow2.start,
    end_time: mardaaniShow2.end,
    provider_sub_location: "Screen 1",
    capacity_total: 100,
    capacity_remaining: 48,
    ticket_pricing: { SILVER: 220, GOLD: 320, RECLINER: 450 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-border2-1",
    listing_id: "listing-movie-border2",
    venue_id: "venue-pvr-ambience",
    city_id: "city-gurugram",
    start_time: borderShow.start,
    end_time: borderShow.end,
    provider_sub_location: "Screen 4",
    capacity_total: 160,
    capacity_remaining: 130,
    ticket_pricing: { SILVER: 180, GOLD: 280, RECLINER: 380 },
    seat_layout: (() => {
      const rows = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"];
      const columns = 16;
      const seat_category_map = {};

      rows.forEach((row) => {
        for (let col = 1; col <= columns; col += 1) {
          const seatId = `${row}${col}`;
          if (row === "A" || row === "B") {
            seat_category_map[seatId] = "RECLINER";
          } else if (row === "C" || row === "D" || row === "E" || row === "F") {
            seat_category_map[seatId] = "GOLD";
          } else {
            seat_category_map[seatId] = "SILVER";
          }
        }
      });

      return {
        version: 2,
        rows,
        columns,
        aisles_after: [4, 8, 12],
        seat_category_map,
        categories: [
          { key: "RECLINER", label: "Recliner", color: "#f59e0b", price: 380, rows: ["A", "B"] },
          { key: "GOLD", label: "Gold", color: "#3b82f6", price: 280, rows: ["C", "D", "E", "F"] },
          { key: "SILVER", label: "Silver", color: "#22c55e", price: 180, rows: ["G", "H", "I", "J"] },
        ],
      };
    })(),
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-tuyaamain-1",
    listing_id: "listing-movie-tuyaamain",
    venue_id: "venue-pvr-ambience",
    city_id: "city-gurugram",
    start_time: tuShow.start,
    end_time: tuShow.end,
    provider_sub_location: "Screen 2",
    capacity_total: 120,
    capacity_remaining: 70,
    ticket_pricing: { SILVER: 200, GOLD: 300, RECLINER: 420 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-mltr-1",
    listing_id: "listing-event-mltr",
    venue_id: "venue-gymkhana",
    city_id: "city-gurugram",
    start_time: mltrShow.start,
    end_time: mltrShow.end,
    provider_sub_location: "Main Stage",
    capacity_total: 2500,
    capacity_remaining: 1700,
    ticket_pricing: { SILVER: 1999, GOLD: 3499, VIP: 4999 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-aujla-1",
    listing_id: "listing-event-aujla",
    venue_id: "venue-gymkhana",
    city_id: "city-gurugram",
    start_time: aujlaShow.start,
    end_time: aujlaShow.end,
    provider_sub_location: "Arena",
    capacity_total: 1800,
    capacity_remaining: 600,
    ticket_pricing: { REGULAR: 2499, FANPIT: 4999, VIP: 6999 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-comiccon-1",
    listing_id: "listing-event-comiccon",
    venue_id: "venue-gymkhana",
    city_id: "city-gurugram",
    start_time: comicConDay.start,
    end_time: comicConDay.end,
    provider_sub_location: "Expo Hall",
    capacity_total: 5000,
    capacity_remaining: 1200,
    ticket_pricing: { SINGLE_DAY: 799, WEEKEND: 1999 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-karting-1",
    listing_id: "listing-activity-karting",
    venue_id: "venue-karting",
    city_id: "city-gurugram",
    start_time: kartingSlot.start,
    end_time: kartingSlot.end,
    provider_sub_location: "Track A",
    capacity_total: 120,
    capacity_remaining: 34,
    ticket_pricing: { STANDARD: 675, PRO: 1250 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-museum-1",
    listing_id: "listing-activity-museum",
    venue_id: "venue-karting",
    city_id: "city-gurugram",
    start_time: museumSlot.start,
    end_time: museumSlot.end,
    provider_sub_location: "Gallery 2",
    capacity_total: 300,
    capacity_remaining: 140,
    ticket_pricing: { ADULT: 590, CHILD: 450 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
  {
    id: "occ-comorin-1",
    listing_id: "listing-restaurant-comorin",
    venue_id: "venue-comorin",
    city_id: "city-gurugram",
    start_time: comorinSlot.start,
    end_time: comorinSlot.end,
    provider_sub_location: "Dining Hall",
    capacity_total: 120,
    capacity_remaining: 22,
    ticket_pricing: { TABLE_FOR_TWO: 1200, TABLE_FOR_FOUR: 2400 },
    seat_layout: null,
    status: OCCURRENCE_STATUS.SCHEDULED,
  },
];

export const mockOffers = [
  {
    id: "offer-welcome50",
    code: "WELCOME50",
    title: "Welcome Offer",
    description: "Flat 50 percent up to Rs 200",
    discount_type: "PERCENT",
    discount_value: 50,
    min_order_value: 300,
    max_discount_value: 200,
    valid_from: inDays(-5).start,
    valid_until: inDays(40).start,
    usage_limit: 100000,
    user_usage_limit: 1,
    is_active: true,
    applicability: {
      city_ids: ["city-gurugram"],
      types: ["EVENT", "MOVIE", "ACTIVITY", "RESTAURANT"],
      categories: [],
      listing_ids: [],
    },
  },
  {
    id: "offer-live200",
    code: "LIVE200",
    title: "Live Event Deal",
    description: "Flat Rs 200 off on event tickets",
    discount_type: "FLAT",
    discount_value: 200,
    min_order_value: 1500,
    max_discount_value: 200,
    valid_from: inDays(-1).start,
    valid_until: inDays(15).start,
    usage_limit: 2000,
    user_usage_limit: 2,
    is_active: true,
    applicability: {
      city_ids: ["city-gurugram"],
      types: ["EVENT"],
      categories: ["Music"],
      listing_ids: [],
    },
  },
];

export const mockArtists = [
  {
    id: "artist-diljit",
    name: "Diljit Dosanjh",
    event: "Dil-Luminati",
    image:
      "https://images.unsplash.com/photo-1615109398623-88346a601842?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "artist-aujla",
    name: "Karan Aujla",
    event: "P-Pop Culture",
    image:
      "https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "artist-arijit",
    name: "Arijit Singh",
    event: "Soulful Night",
    image:
      "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "artist-badshah",
    name: "Badshah",
    event: "Paagal Tour",
    image:
      "https://images.unsplash.com/photo-1566753323558-f4e0952af115?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "artist-shreya",
    name: "Shreya Ghoshal",
    event: "Live in Concert",
    image:
      "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "artist-honey",
    name: "Honey Singh",
    event: "Glory Tour",
    image:
      "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=300&q=80",
  },
];

export const mockUser = {
  id: "user-demo-1",
  name: "Riya Patel",
  email: "riya@example.com",
  phone: "+91-9876543210",
  profile_image_url: "",
  role: USER_ROLE.USER,
  is_active: true,
  is_temporary_password: false,
  stats: {
    total_bookings: 5,
    upcoming_bookings: 2,
    total_spent: 15800,
  },
};

export const mockAdminUser = {
  id: "admin-demo-1",
  name: "System Admin",
  email: "admin@citiconnect.com",
  phone: "+91-9000000000",
  profile_image_url: "",
  role: USER_ROLE.ADMIN,
  is_active: true,
  is_temporary_password: false,
};

export const initialMockNotifications = [
  {
    id: "notif-1",
    user_id: "user-demo-1",
    title: "Booking Confirmed",
    body: "Your booking for Mardaani 3 is confirmed.",
    type: "BOOKING",
    reference_id: "booking-demo-1",
    is_read: false,
    created_at: inDays(-1).start,
  },
  {
    id: "notif-2",
    user_id: "user-demo-1",
    title: "Offer on Wishlisted Listing",
    body: "LIVE200 is now active for Karan Aujla Tour.",
    type: "OFFER",
    reference_id: "listing-event-aujla",
    is_read: false,
    created_at: inDays(-2).start,
  },
];

export const initialMockBookings = [
  {
    id: "booking-demo-1",
    user_id: "user-demo-1",
    occurrence_id: "occ-mardaani-1",
    listing_snapshot: {
      listing_id: "listing-movie-mardaani3",
      title: "Mardaani 3",
      type: LISTING_TYPE.MOVIE,
      city_name: "Gurugram",
    },
    booked_seats: ["C5", "C6"],
    ticket_breakdown: { GOLD: 2 },
    quantity: 2,
    unit_price: 320,
    total_price: 640,
    applied_offer_id: null,
    discount_amount: 0,
    final_price: 640,
    currency: "INR",
    status: BOOKING_STATUS.CONFIRMED,
    payment_provider: "MOCK",
    payment_ref: "MOCK-TXN-10001",
    cancellation_reason: "",
    hold_expires_at: null,
    can_cancel: true,
    cancellation_deadline: inDays(0, 17, 0).start,
    created_at: inDays(-1).start,
    updated_at: inDays(-1).start,
  },
];

export const initialMockWishlist = ["listing-event-aujla", "listing-restaurant-comorin"];

export const initialMockAuditLogs = [
  {
    id: "log-1",
    admin_user: "System Admin",
    action: "CREATE_LISTING",
    entity_type: "LISTING",
    entity_id: "listing-event-mltr",
    diff: { title: "Michael Learns to Rock Live", status: LISTING_STATUS.PUBLISHED },
    created_at: inDays(-4).start,
  },
  {
    id: "log-2",
    admin_user: "System Admin",
    action: "UPDATE_OFFER",
    entity_type: "OFFER",
    entity_id: "offer-welcome50",
    diff: { is_active: true },
    created_at: inDays(-2).start,
  },
  {
    id: "log-3",
    admin_user: "System Admin",
    action: "CREATE_OCCURRENCE",
    entity_type: "OCCURRENCE",
    entity_id: "occ-mltr-1",
    diff: { listing_id: "listing-event-mltr", provider_sub_location: "Main Stage" },
    created_at: inDays(-1).start,
  },
];
